CREATE TABLE "ADMIN"."MOVIE" 
   (	"MOVIE_ID" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"BUDGET" NUMBER, 
	"GROSS" NUMBER, 
	"LIST_PRICE" NUMBER, 
	"GENRES" JSON, 
	"SKU" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"YEAR" NUMBER, 
	"OPENING_DATE" DATE, 
	"VIEWS" NUMBER, 
	"CAST" JSON, 
	"CREW" JSON, 
	"STUDIO" JSON, 
	"MAIN_SUBJECT" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"AWARDS" JSON, 
	"NOMINATIONS" JSON, 
	"RUNTIME" NUMBER, 
	"SUMMARY" CLOB COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP"   NO INMEMORY ;

CREATE UNIQUE INDEX "ADMIN"."PK_MOVIE_ID" ON "ADMIN"."MOVIE" ("MOVIE_ID") 
  ;

ALTER TABLE "ADMIN"."MOVIE" ADD CONSTRAINT "PK_MOVIE_ID" PRIMARY KEY ("MOVIE_ID")
  USING INDEX "ADMIN"."PK_MOVIE_ID"  ENABLE;

